# Jinja variables help maintain the recipe as you'll update the version only here.
{% set ver = "1.5.0" %}
{% set beta = "beta20161111" %}
{% set version = ver + "_" + beta %}
{% set commit = "38acdc5f41d7d3bb90b8908c15083019e5fd8384" %}

package:
    name: pyngl
    version: {{ version }}

source:
    git_url: git@github.com:NCAR/pyngl.git
    git_rev: {{ commit }}

build:
    number: 0
    skip: True  # [win or linux32]


requirements:
    build:
        - gcc
        - libnetcdf 4.4.*
        - proj4 4.9.3
        - gdal 1.11.*
        - g2clib 1.6.*
        - hdfeos2
        - hdfeos5
        - jasper
        - libpng
        - jpeg
        - zlib
        - hdf4
        - hdf5
        - libiconv
        - curl
        - cairo [linux]
        - expat
        - udunits2
        - bzip2
        - gsl
        - ncl
        - python 2.*
        - numpy x.x
    run:
        - libgcc
        - libnetcdf 4.4.*
        - proj4 4.9.3
        - gdal 1.11.*
        - g2clib 1.6.*
        - hdfeos2
        - hdfeos5
        - jasper
        - libpng
        - jpeg
        - zlib
        - hdf4
        - hdf5
        - libiconv
        - curl
        - cairo [linux]
        - expat
        - udunits2
        - bzip2
        - gsl
        - ncl
        - python 2.*
        - numpy x.x

test:
  requires:
    - nose
  imports:
    - Ngl
  commands:
    - cd $SRC_DIR/src/examples && for file in xy2.py; do echo $file ; nosetests $file ; done | tee pyngl-test.log

