{% set ver = "6.4.0" %}
{% set beta = "beta20161111" %}
{% set version = ver + "_" + beta %}

package:
    name: ncl
    version: {{ version }}

source:
    git_url: git@github.com:NCAR/ncl.git
    git_rev: master

build:
    number: 0
    skip: True  # [win or py3k]
    detect_binary_files_with_prefix: true

requirements:
    build:
        - gcc
        - libnetcdf 4.4.*
        - proj4 4.9.3
        - gdal 1.11.*
        - g2clib 1.6.*
        - hdfeos2
        - hdfeos5
        - jasper
        - libpng
        - jpeg
        - zlib
        - hdf4
        - hdf5
        - libiconv
        - curl
        - cairo [linux]
        - udunits2
        - bzip2
        - gsl
    run:
        - libgcc
        - libnetcdf 4.4.*
        - hdf4
        - proj4 4.9.3
        - gdal 1.11.*
        - libuuid [osx]
        - g2clib 1.6.*
        - hdfeos2
        - hdfeos5
        - jasper
        - libgfortran
        - libpng
        - jpeg
        - zlib
        - hdf4
        - hdf5
        - libiconv
        - curl
        - cairo [linux]
        - udunits2
        - bzip2
        - gsl

test:
    commands:
        - ncl -V
        - NCARG_ROOT=${PREFIX} ${SRC_DIR}/install/make-tarfile/check_files | grep '^<' | grep -v '^< bin/ESMF_RegridWeightGen' && exit 1 || exit 0

about:
    home: http://ncl.ucar.edu/
    summary: 'NCAR Command Language'

extra:
    recipe-maintainers:
        - khallock
        - marylhaley
        - david-ian-brown
