# Jinja variables help maintain the recipe as you'll update the version only here.
{% set version = "6.4.0_beta20160818" %}

package:
    name: ncl
    version: {{ version }}

source:
    fn: ncl_ncarg-{{ version }}.tar.gz
    url: https://www.ncl.ucar.edu/Download/files/ncl_ncarg-{{ version }}.tar.gz
    # md5 is OK but sha256 is desirable.
    sha256: 9102b09b661670b10a445562816943c0a90d298bf7ddb047ecab7e22627aa41c

build:
    number: 0
    skip: True  # [win or linux32]

requirements:
    build:
        - libpng
        - jasper
        - jpeg
        - zlib
        - hdf4
        - hdf5
        - gcc
        - libnetcdf 4.4.*
        - proj.4
        - hdfeos2
        - g2clib
        - gdal 2.1.*
        - libiconv
        - hdfeos5
        - curl
        - cairo [linux]
        - udunits2
        - bzip2
    run:
        - libgcc
        - libpng
        - jasper
        - jpeg
        - zlib
        - libnetcdf 4.4.*
        - hdf5
        - hdf4
        - proj.4
        - hdfeos2
        - g2clib
        - gdal 2.1.*
        - libiconv
        - hdfeos5
        - curl
        - cairo [linux]
        - udunits2
        - bzip2


test:
    commands:
        - ncl -V
        - NCARG_ROOT=${PREFIX} ${SRC_DIR}/install/make-tarfile/check_files | grep '^<' | grep -v '^< bin/ESMF_RegridWeightGen' && exit 1 || exit 0


about:
    home: http://ncl.ucar.edu
    # license: MIT
    summary: 'NCAR Command Language'

extra:
    recipe-maintainers:
        - khallock
